In [1]:
import numpy as np
import pandas as pd

In [2]:
import math

In [3]:
rating_columns = ["UserId", "MovieId", "Rating", "TimeStamp"]
rating_dat = pd.read_table("ml-1m/ratings.dat", sep="::", names=rating_columns)

/home/vedant/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [4]:
### Train(0.80) test(0.20) random split 

train_rating_dat = rating_dat.sample(frac = 0.8, random_state=201)
test_rating_dat = rating_dat.drop(train_rating_dat.index)

train_users = max(train_rating_dat["UserId"])
train_movies = max(train_rating_dat["MovieId"])

test_users = max(test_rating_dat["UserId"])
test_movies = max(test_rating_dat["MovieId"])

assert train_users == test_users
assert train_movies == test_movies

In [5]:
train_rating_matrix = train_rating_dat.pivot(index = 'UserId', columns='MovieId', values='Rating')
test_rating_matrix = test_rating_dat.pivot(index = 'UserId', columns='MovieId', values='Rating')

In [101]:
users = max(ratings["UserId"])
movies = max(ratings["MovieId"])

UserId  MovieId  Rating  TimeStamp
16            1     2687       3  978824268
22            1     1270       5  978300055
26            1     1097       4  978301953
27            1     1721       4  978300055
31            1     3186       4  978300019
...         ...      ...     ...        ...
1000184    6040     2791       4  956715569
1000187    6040     2003       1  956716294
1000192    6040     2019       5  956703977
1000194    6040     1077       5  964828799
1000200    6040     2028       5  956704519

[200042 rows x 4 columns]

In [102]:
%%time

rating_matrix_dat = rating_dat.pivot(index = 'UserId', columns = 'MovieId', values = 'Rating').fillna(0)
rating_matrix = np.asarray(rating_matrix_dat)

CPU times: user 1.19 s, sys: 168 ms, total: 1.36 s
Wall time: 993 ms


In [108]:
rating_matrix[0].nonzero()

(array([   0,   47,  144,  253,  513,  517,  574,  580,  581,  593,  639,
         689,  708,  740,  853,  858,  877,  957,  963,  964,  970, 1025,
        1104, 1107, 1117, 1154, 1178, 1195, 1421, 1439, 1574, 1658, 1727,
        1781, 1782, 1838, 1848, 2102, 2128, 2147, 2162, 2205, 2483, 2488,
        2557, 2586, 2592, 2599, 2710, 2889, 2898, 2969, 3177]),)

In [103]:
### For testing matrix 0.20 testing

start_row = math.floor(rating_matrix.shape[0] * 0.20)
start_col = math.floor(rating_matrix.shape[1] * 0.20)
test_rating_matrix = np.zeros((start_row, start_col))

In [96]:
### User-User colabarative filtering

def mean_center(A):
    mean_centered_A = np.zeros(A.shape)
    for row in range(len(A.shape[0])):
        ratings_sum = A[row].sum()
        movies_rated = (A[row] > 0).sum()
        mean = ratings_sum/movies_rated
        mean[row] = A[row] - mean

In [52]:
mean_centered_A = mean_center(A)

/home/vedant/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars
  


In [64]:
new = np.zeros((2,2))
newb = np.zeros((2,2))

In [65]:
new[0][0]= 1

In [72]:
newc = np.asarray([0,1])

array([0, 1])

In [68]:
newb

array([[1., 0.],
       [0., 0.]])

In [69]:
mean_centered_A

array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [-4.18867925,  0.81132075, -4.18867925, ..., -4.18867925,
        -4.18867925, -4.18867925],
       [-3.71317829, -3.71317829, -3.71317829, ..., -3.71317829,
        -3.71317829, -3.71317829],
       ...,
       [-3.8       , -3.8       , -3.8       , ..., -3.8       ,
        -3.8       , -3.8       ],
       [-3.87804878, -3.87804878, -3.87804878, ..., -3.87804878,
        -3.87804878, -3.87804878],
       [-3.57771261, -0.57771261, -3.57771261, ..., -3.57771261,
        -3.57771261, -3.57771261]])